name: worldapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: 1.3.0
  cloud_firestore: 0.9.9
  circular_check_box: 0.0.2
  flutter_rating: 0.0.2
  font_awesome_flutter: 8.4.0
  firebase_auth: 0.8.3
  flutter_custom_clippers: 0.1.6
  fluttertoast: 3.0.3
  gradient_widgets: 0.3.1
  google_sign_in: 4.0.1+1
  image_picker: 0.5.0+9
  url_launcher: 5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imageHeader/london.jpg
    - assets/imageHeader/newyork.jpg
    - assets/imageHeader/paris.jpg
    - assets/imageHeader/sydney.jpg
    - assets/icons/100.png
    - assets/icons/200.png
    - assets/icons/300.png
    - assets/icons/400.png
    - assets/icons/500.png
    - assets/gif/loading.gif
    - assets/iconsetting/icon-bookmark.png
    - assets/iconsetting/icon-email.png
    - assets/iconsetting/icon-exit.png
    - assets/iconsetting/icon-home.png
    - assets/iconsetting/icon-lock.png
    - assets/iconsetting/icon-more.png
    - assets/iconsetting/icon-share.png
    - assets/iconsetting/icon-star.png
    - assets/iconsetting/icon-world.png
    - assets/imageProfile/account.png
    - assets/iconsflag/icon_england_flag.png
    - assets/iconsflag/icon_vietnam_flag.png
    - assets/iconsflag/icon_china_flag.png
    - assets/imageRegister/login_demo.png
    - assets/imageRegister/signup_demo.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
